let _tempLanguages: Array<any> = new Array();

_tempLanguages['fr-FR'] =  {
    "HOME":"Accueil",
    "WELCOME":"Bienvenue!",
    "GUIDE_DEC":"Guide Découverte",
    "GUIDES_ITI":"Guides / Itinéraires",
    "GUIDES_DEC":"Guides découverte",
    "ITINERARIES":"Itinéraires",
    "ITINERARY":"Itinéraire",
    "ITINERARY_LIST":"Liste itinéraires",
    "SHOW_ITINERARY_LIST":"Afficher la liste des itinéraires",
    "CHOICE_ITINERARY":"Choisir votre itinéraire",
    "PRESENTATION":"Présentation",
    "ORDER_GUIDE":"Commander guide",
    "PREP_GUIDE":"Guide en préparation",
    "EDITED_GUIDE":"Guide edité",
    "DISCOVERY_GUIDE":"Guide decouverte",
    "OBJECTS":"Objets",
    "THEMES":"Thèmes",
    "FOCUS":"Focus",
    "OBJECTS_LIST":"Objets, Thèmes, Focus",
    "RGSMAP_LEGEND":"Légende",
    "RGSMAP_ITINERARY":"Tracé du parcours",
    "RGSMAP_BTN_SHOW":"Voir",
    "RGSMAP_BTN_SHOW_DESC":"Clic pour afficher le panorama",
    "RGSMAP_BTN_ITINERARY":"Itinéraire",
    "RGSMAP_BTN_ITINERARY_DESC":"Clic pour revenir à l'état initial",
    "RGSMAP_WEBSITES":"Sites des communes",
    "RGSMAP_ACTIONS_DD":"Actions DD",
    "LOADING":"Chargement",
    "GET_ALL_PRINCIPLES":"Voir tous les principes",
    "SHOW_WEBSITE":"Voir le site",
    "ADD_FAVORIT":"Ajouter un favorit?",
    "CONFIRM_SAVE_FAVORIT":"Voulez-vous sauvegarder le favorit?",
    "CONFIRM_SAVE_POINT":"Voulez-vous sauvegarder le point?",
    "CONFIRM_REMOVE_POINT":"Voulez-vous supprimer le favorit?",
    "ITINERARY_COVER_TITLE":"Couverture de l'itinéraire",
    "ITINERARY_HOME": "Accueil de l'itinéraire",
    "ITEMS":"Eléments",
    "INFOS":"Informations",
    "SHOW_MAP":"Afficher la carte",
    "FAVORITES":"Favorits",
    "FAVORIT":"Favorit",
    "FB_ERROR_AUTH": "Erreur sur l'authentification",
    "FB_UNDEFINED_DB": "Base de données pas definie",
    "FB_UNDEFINED_DB_NAME": "Nom de la base de données pas defini",
    "FB_UNDEFINED_PATH": "Pas de chemin defini",
    "FB_UNDEFINED_ITEM_TO_EDIT": "Pas d'élément à modifier dans Firebase",
    "FB_UNDEFINED_ITEM_TO_DELETE": "Pas d'élément à supprimer dans Firebase",
    "ASDD_REJECT_JSON": "Service ASDD: Json rejeté",
    "ASDD_AJAX_ERROR": "Service ASDD: Erreur ajax",
    "LINK_DD":"Lien Développement Durable",
    "DID_YOU_KNOW": "Le saviez vous ?",
    "TO_KNOW_MORE": "Pour en savoir plus...",
    "PHOTOS": "Photos",
    "USER_ADMIN": "Administration",
    "USER_LOGIN": "Connexion",
    "USER_CREATE_ACCOUNT": "Créer un compte",
    "USER_LOGOUT": "Déconnecter",
    "USER_CONFIRM_LOGOUT": "Voulez-vous VRAIMENT vous déconnecter ?",
    "CONFIRM_DISGREE": "Annuler",
    "CONFIRM_AGREE": "OK"
};
_tempLanguages['en-UK'] =  {
    "HOME":"Home",
    "WELCOME":"Welcome!",
    "GUIDE_DEC":"Discovery Guide",
    "GUIDES_ITI":"Guides / Itineraries",
    "GUIDES_DEC":"Discovery Guides",
    "ITINERARIES":"Itineraries",
    "ITINERARY":"Itinerary",
    "ITINERARY_LIST":"List of itineraries",
    "SHOW_ITINERARY_LIST":"View the list of itineraries",
    "CHOICE_ITINERARY":"Choice your itinerary",
    "PRESENTATION":"Presentation",
    "ORDER_GUIDE":"Order guide",
    "PREP_GUIDE":"Guide in preparation",
    "EDITED_GUIDE":"Edited guide",
    "DISCOVERY_GUIDE":"Discovery guide",
    "OBJECTS":"Objects",
    "THEMES":"Themes",
    "FOCUS":"Focus",
    "OBJECTS_LIST":"Objects, Themes, Focus",
    "RGSMAP_LEGEND":"Legend",
    "RGSMAP_ITINERARY":"Course layout",
    "RGSMAP_BTN_SHOW":"View",
    "RGSMAP_BTN_SHOW_DESC":"Click to display the panorama",
    "RGSMAP_BTN_ITINERARY":"Itinerary",
    "RGSMAP_BTN_ITINERARY_DESC":"Click to return to the initial state",
    "RGSMAP_WEBSITES":"Municipal sites",
    "RGSMAP_ACTIONS_DD":"DD Actions",
    "LOADING":"Loading",
    "GET_ALL_PRINCIPLES":"See all principles",
    "SHOW_WEBSITE":"See the website",
    "ADD_FAVORIT":"Add favorit?",
    "CONFIRM_SAVE_FAVORIT":"Do you want to save the favorit?",
    "CONFIRM_SAVE_POINT":"Do you want to save the point?",
    "CONFIRM_REMOVE_POINT":"Do you want to remove the favorit?",
    "ITINERARY_COVER_TITLE":"Itinerary coverage",
    "ITINERARY_HOME": "Home of the itinerary",
    "ITEMS":"Items",
    "INFOS":"Informations",
    "SHOW_MAP":"Show map",
    "FAVORITES":"Favorits",
    "FAVORIT":"Favorit",
    "FB_ERROR_AUTH": "Error on Auth",
    "FB_UNDEFINED_DB": "Database not defined",
    "FB_UNDEFINED_DB_NAME": "Database name not defined",
    "FB_UNDEFINED_PATH": "No path defined",
    "FB_UNDEFINED_ITEM_TO_EDIT": "No item to edit in Firebase",
    "FB_UNDEFINED_ITEM_TO_DELETE": "No item to delete in Firebase",
    "ASDD_REJECT_JSON": "ASDD Service: Reject json",
    "ASDD_AJAX_ERROR": "ASDD Service: Ajax error",
    "LINK_DD":"Sustainable Development Link",
    "DID_YOU_KNOW": "Did you know ?",
    "TO_KNOW_MORE": "To know more...",
    "PHOTOS": "Photos",
    "USER_ADMIN": "Administration",
    "USER_LOGIN": "Login",
    "USER_CREATE_ACCOUNT": "Create account",
    "USER_LOGOUT": "Logout",
    "USER_CONFIRM_LOGOUT": "Do you REALLY want to log out?",
    "CONFIRM_DISGREE": "Disagree",
    "CONFIRM_AGREE": "Agree"
};

export let Languages:Array<any> = _tempLanguages;